name = "RebuiltFromSands"
author = "Killerqu00"
version = "alpha4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a90817319980213b77dd89b62ddc96ab28cb96c15dd9b4f9ae7284bf0e55a92"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
