name = "Rebuilt From Sands"
author = "Killerqu00"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b48963a7fc073f17efab249531354a818056aaf16cd91485de7069afb11f4633"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
