name = "RebuiltFromSands"
author = "Killerqu00"
version = "alpha4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e0cff0ba229f165fff2f57e45681b351ba940f9131e682c7ea6befc5e9a86cb"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
