name = "RebuiltFromSands"
author = "Killerqu00"
version = "alpha5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aa230f654e818560e3788da85a6f7c97dd353bd3b7162dd78ef54ee1832b461"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
