ServerEvents.recipes(event => {
    event.remove({output:'mekanism:basic_control_circuit'})
    event.shapeless(
        'mekanism:basic_control_circuit',
        [
            'immersiveengineering:circuit_board',
            'immersiveengineering:electron_tube',
            '#forge:wires/electrum',
            '#forge:dusts/redstone'
        ]
    )
    event.shaped(
        Item.of('custommachinery:custom_machine_item', '{machine:"custommachines:sand_drill"}'),
        [
            'PCP',
            'RFR',
            'PDP'
        ],
        {
            P: '#forge:plates/steel',
            C: 'mekanism:basic_control_circuit',
            R: '#forge:dusts/redstone',
            F: 'mekanism:steel_casing',
            D: 'immersiveengineering:drillhead_steel'
        }
    )
    event.remove({output:'mekanism:steel_casing'})
    event.shaped(
        'mekanism:steel_casing',
        [
            'SRS',
            'RCR',
            'SRS'
        ],
        {
            S:'#forge:ingots/steel',
            R:'#forge:rods/steel',
            C:'#forge:circuits/basic'
        }
    )
    event.remove({output:'mekanism:metallurgic_infuser'})
    event.shaped(
        'mekanism:metallurgic_infuser',
        [
            'ORO',
            'FCF',
            'OOO'
        ],
        {
            O:'#forge:ingots/osmium',
            R:'#forge:rods/gold',
            F:'minecraft:furnace',
            C:'mekanism:steel_casing'
        }
    )
    event.remove({output:'mekanism:advanced_control_circuit'})
    event.shapeless(
        'mekanism:advanced_control_circuit',
        [
            '#forge:circuits/basic',
            '#forge:alloys/advanced',
            '#forge:alloys/advanced',
            '#forge:alloys/advanced',
            '#forge:alloys/advanced',
            '#forge:wires/electrum',
            '#forge:wires/electrum',
            '#forge:wires/electrum',
            '#forge:wires/electrum'
        ]
    )
    event.remove({output:'mekanism:basic_fluid_tank'})
    event.remove({output:'mekanism:advanced_fluid_tank'})
    event.remove({output:'mekanism:elite_fluid_tank'})
    event.remove({output:'mekanism:ultimate_fluid_tank'})
    event.shaped(
        'mekanism:basic_fluid_tank',
        [
            'SSS',
            'RGR',
            'SSS'
        ],
        {
            S:'#forge:ingots/steel',
            R:'#forge:rods/steel',
            G:'#forge:glass/colorless'
        }
    )
    event.shaped(
        'mekanism:advanced_fluid_tank',
        [
            'CAC',
            'ATA',
            'CAC'
        ],
        {
            C:'#forge:plates/constantan',
            A:'#forge:alloys/advanced',
            T:'mekanism:basic_fluid_tank'
        }
    )
    event.shaped(
        'mekanism:elite_fluid_tank',
        [
            'OAO',
            'ATA',
            'OAO'
        ],
        {
            O:'#forge:ingots/refined_obsidian',
            A:'#forge:alloys/elite',
            T:'mekanism:advanced_fluid_tank'
        }
    )
    event.shaped(
        'mekanism:ultimate_fluid_tank',
        [
            'NAN',
            'ATA',
            'NAN'
        ],
        {
            N:'#forge:ingots/netherite',
            A:'#mekanism:alloys/atomic',
            T:'mekanism:elite_fluid_tank'
        }
    )
    event.remove({output:'mekanism:configurator'})
    event.shaped(
        'mekanism:configurator',
        [
            '  E',
            ' T ',
            'R  '
        ],
        {
            E:'#forge:rods/electrum',
            T:'mekanism:energy_tablet',
            R:'#forge:rods/treated_wood'
        }
    )
    event.custom({
        type: 'mekanism:enriching',
        input: '8x immersiveengineering:dust_hop_graphite',
        output: 'mekanism:dust_diamond'
    })
})